service: marvin

frameworkVersion: "=1.3"

package:
  exclude:
    - tmp/**
    - .git/**
    - src/**/*test.js

    # Exclude all node modules except for a few
    - node_modules/**
    - '!node_modules/node-fetch/**'

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1

functions:
  handleMessage:
    handler: src/index.handleMessage
    events:
      - http:
          path: marvin
          method: post
