service: marvin

frameworkVersion: "=1.3"

package:
  exclude:
    - tmp/**
    - .git/**
    - src/**/*test.js

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-west-1

functions:
  handleMessage:
    handler: src/lambda.handleMessage
    events:
      - http:
          path: marvin
          method: post
